name: Push Jupyterlab Generic Image to quay

on:
  push:
    paths:
      - jupyterlab-generic/**
      - .github/workflows/build_push_jupyterlab-generic.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: prewk/s3-cp-action@v2
      #   with:
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     source: 's3://ctds-stata/StataNow18Linux64.tar.gz'
      #     dest: './jupyter-pystata-user-licensed/resources/'

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/*/} | tr / _)"
          echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/*/} | tr / _)" >> $GITHUB_ENV

      - name: Login to Quay.io
        id: login
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/cdis/jupyterlab-generic:${{ env.IMAGE_TAG }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: ./jupyterlab-generic
          file: "./jupyterlab-generic/Dockerfile"
          push: true
          tags: |
            quay.io/cdis/jupyterlab-generic:${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
